#!/usr/bin/env node
// Generates css/theme-dark.generated.css from the light stylesheets linked in
// index.html. Hand-tuned tweaks live in css/theme-dark.css, loaded after it.
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { buildDarkOverrides } from "../js/modules/themeColors.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SKIP = new Set(["css/fonts.css", "css/typography.css", "css/theme-dark.css", "css/theme-dark.generated.css"]);

const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
const sheets = [...html.matchAll(/<link[^>]+href="(css\/[^"?]+)[^"]*"[^>]*>/g)]
  .map((m) => m[1])
  .filter((href) => !SKIP.has(href));

let out = "/* Generated by scripts/build_dark_theme.mjs — do not edit by hand. */\n";
for (const href of sheets) {
  const css = fs.readFileSync(path.join(ROOT, href), "utf8");
  out += `\n/* ---- ${href} ---- */\n` + buildDarkOverrides(css);
}
fs.writeFileSync(path.join(ROOT, "css/theme-dark.generated.css"), out);
process.stdout.write(`Wrote css/theme-dark.generated.css from ${sheets.length} stylesheets (${out.length} bytes)\n`);
